### ISSUE TITLE
Replace the Raspberry Pi 4 with a Raspberry Pi Zero

### ISSUE THREAD

**Issue by keenanjohnson** [keenanjohnson/ghg-gas-cloud#5]

**Comment by chrisys** [comment]
Also worth a look at the NanoPi Neo Air - performance is considerably better than a Pi Zero for similar cost, although not as easy to obtain 👍

**Comment by keenanjohnson** [comment]
Thanks for the suggestion @chrisys ! I'll check it out and evaluate it!

**Comment by keenanjohnson** [comment]
The NanoPi Neo Air seems great, but too hard to purchase and above my current budget for the needs right now.

**Comment by keenanjohnson** [comment]
Swapped my prototype to a raspberry pi zero
![IMG_8494 2](https://user-images.githubusercontent.com/2559382/121610307-8aacdb80-ca0a-11eb-8ba4-f9bc9dd76cbd.JPG)
