### ISSUE TITLE
Consider What Database Option is Best for the Project

### ISSUE THREAD

**Issue by keenanjohnson** [keenanjohnson/ghg-gas-cloud#9]
I'm currently using InfluxDB to store the timeseries greenhouse gas data. I'm not sure if this is the correct solution, so I need to look into other options.

I've seen https://thingsboard.io/ which seems promising. The most interesting feature is that it has a Map visualization widget that could be used to easily create a nice public dashboard.

Definitely open to any other suggestions that anyone has.

**Comment by keenanjohnson** [comment]
Thanks for the suggestions @phil-d-wilson!

I'm currently using Influx for logging all the time series data and I'm looking for a good solution to create a nice public-facing dashboard that would allow access to the data and probably have some sort of nice map display.

I'll look into the other options and let you know! Certainly I'll reach out if I hit any balena roadblocks :)

**Comment by phil-d-wilson** [comment]
Maybe the [dashboard balenaBlock](https://github.com/balenablocks/dashboard) with the [worldmap plugin](https://grafana.com/grafana/plugins/grafana-worldmap-panel/) ?

**Comment by keenanjohnson** [comment]
Yeah, it seems like the standard thing would be InfluxDB -> Grafana -> World Map Plugin. I'd like a centralized database to store all the data from multiple Balena devices in the central database. I was hoping for a solution that wouldn't involve two tools (InfluxDB + Grafana) to keep cost down, but it might be the best solution.

**Comment by lalligagger** [comment]
+1 for influx which I've hooked up to Dash with no problem (not a Grafana fan, gives me flashbacks to TVAC testing 😅)

**Comment by keenanjohnson** [comment]
Cool yeah I haven't really looked at Dash yet, but I'll check that out.

**Comment by keenanjohnson** [comment]
Ok it seems like InfluxDB + Dash for visualization is the best option for now, so going to proceed with that :)
